# site properties and page defaults
title: MOFAI
subtitle: Mathematical Foundations of AI
description: Welcome to MOFAI, a platform dedicated to exploring the critical mathematical principles that drive the field of Artificial Intelligence. From linear algebra to probability theory, our mission is to bridge the gap between theory and application, helping researchers, students, and enthusiasts deepen their understanding of AI's mathematical underpinnings. Dive into in-depth resources, research articles, and discussions designed to equip you with the knowledge needed to excel in the rapidly evolving AI landscape.
header: images/background.jpg
footer: images/background.jpg
# proofer: false

# site social media and other links
links:
  email: zahra.monfared@iwr.uni-heidelberg.de
  orcid: 0049-6221-8713-9213
  google_scholar: https://scholar.google.com/citations?user=OPUIwIoAAAAJ&hl=en&oi=ao
  github: MahshidBaharifar
  twitter: MahshidBaharifarDESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: MahshidBaharifarDESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
